JakeTWright1/WOT2BE

app/controllers/jobs_controller.rb
- Added index method to jobs controller
=> added index method to jobs controller

.gitignore, yarn.lock
added to git ignore so that cloudinary nodes wont be added
=> added to git ignore so that cloudinary nodes wont be added

app/views/devise/registrations/new.html.erb, db/migrate/20230902104823_add_worker_to_user.rb, db/schema.rb
- Updated sign up form to include checkbox to sign up as worker
- New migration to update schema - adeed worker column to user model
=> added worker boolean to user model

app/controllers/jobs_controller.rb, app/models/job.rb, config/environments/development.rb, config/routes.rb, config/storage.yml, db/migrate/20230902113108_create_active_storage_tables.active_storage.rb, db/schema.rb
- added routes for jobs (new, create, show)
- added database migrations for cloudinary
=> added job routes and database migrations for cloudinary

app/controllers/jobs_controller.rb
-Added show method to jobs controller
-Added set_job method
=> Jobs show method

app/controllers/jobs_controller.rb, app/models/job.rb, app/views/jobs/new.html.erb, app/views/pages/home.html.erb, config/storage.yml, db/schema.rb
- added an upload form and linked it with cloudinary
=> created a video upload formand linked it with cloudinary

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_job_profile.scss, app/assets/stylesheets/components/_logo.scss, app/controllers/jobs_controller.rb, app/views/jobs/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_job_profile.html.erb, db/migrate/20230902132514_add_user_to_jobs.rb, db/schema.rb
- Added html for job profile show page
- Updated CSS for show page and application body
=> Job show html

app/controllers/users_controller.rb, test/controllers/users_controller_test.rb
- generated controller for User model
=> generated users controller

app/controllers/jobs_controller.rb, config/routes.rb
- Created app routes for jobs and users
- Update jobs controller with strong params and methods
=> Added routes for app & methods in jobs controller

app/controllers/jobs_controller.rb, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, db/schema.rb
- added video player to home screen which plays jobs video's
=> added video to home screen through active record

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_logo.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb
=> home layout

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/application_controller.rb, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb
- Navbar for all application
- Logic for displaying upload function for worker users 
- added worker boolean to user
=> basic navbar and logic for students/workers

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, db/migrate/20230908091513_add_username_to_users.rb, db/schema.rb
- Username column added to the users table
- Validations added to User model
=> username added to users column

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search.scss, app/controllers/users_controller.rb, app/javascript/controllers/navbar_controller.js, app/models/user.rb, app/views/jobs/new.html.erb, app/views/layouts/_navbar.html.erb, app/views/users/show.html.erb
- Working links added to Navbar 
- Stimulus popup for search bar will need to be fixed - It only pops up momentarily before disappearing again
=> Add links to navbar

app/assets/stylesheets/components/_logo.scss, app/views/layouts/_logo.html.erb, app/views/pages/home.html.erb
- Made logo static on page so won't scroll with videos
- Moved logo into partial
=> fixed logo

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
- Added link on homepage to navigate to job profile page
=> added link to job profile

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_user_profile.scss, app/views/users/show.html.erb
- Generated user show page 
- To Do: Implement favourites partial to display saved jobs
=> User profile page

app/assets/stylesheets/components/_fav.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_job_infos.scss, app/assets/stylesheets/components/_job_profile.scss, app/assets/stylesheets/components/_logo.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_job_profile.html.erb
- New logo for site - More modern and less of an eyesore
- Updated navbar to be more attention grabbing
- added "Uploaded by" display on videos page
=> Updated home design

app/assets/stylesheets/components/_fav.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_job_profile.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/_navbar.html.erb, app/views/shared/_job_profile.html.erb
- Added button to job profile to save favorites
- Just need to build functionality to get this to join the job and the user
=> added fav button to job profile

app/controllers/jobs_controller.rb, app/models/industry.rb, app/models/job.rb, app/models/jobindustry.rb, app/views/jobs/new.html.erb, db/migrate/20230911184525_create_industries.rb, db/migrate/20230911185220_create_jobindustries.rb, db/migrate/20230911191740_add_industry_to_jobs.rb, db/schema.rb, db/seeds.rb, test/models/industry_test.rb, test/models/jobindustry_test.rb
- Added industry model
- Updated seed file
- Updated database with associations between Job and Industry models
=> added Industry model

Gemfile.lock, app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_job_profile.scss, app/views/shared/_job_profile.html.erb, config/storage.yml
=> New job profile

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_job_profile.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_job_profile.html.erb
- Fixed navbar and job profile page
=> front-end cleanup

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
- Added snap on scroll for each video
- Need to fix the captions stacking on top of each other
=> Snap on scroll

app/controllers/users_controller.rb, app/views/pages/home.html.erb, app/views/users/index.html.erb, config/routes.rb
- Added a new page to show search results 
- Added a search function but it doesnt work yet
=> added a page to show search results

app/assets/stylesheets/components/_job_profile.scss, app/views/shared/_job_profile.html.erb
- Tabs now clickable on Profile page
=> responsive profile tabs

app/views/shared/_job_profile.html.erb
- Fav button updates when favourite already exists
=> favourites updated

app/controllers/jobs_controller.rb, app/controllers/users_controller.rb, app/views/jobs/index.html.erb, app/views/layouts/_navbar.html.erb, app/views/pages/home.html.erb, app/views/users/index.html.erb, config/routes.rb
- added search function
- some formating of cards done in jobs.veiw.hmtl
=> search completed

app/assets/stylesheets/components/_job_profile.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search.scss, app/controllers/jobs_controller.rb, app/views/jobs/index.html.erb, app/views/layouts/_navbar.html.erb, app/views/pages/home.html.erb, app/views/shared/_job_profile.html.erb
- added subjects to search function in controller
- linked subject buttons to search on jobs profile page 
- We need to update the condition for industries to validate if user input is present in the Industry table 
- Updated navbar search and removed search bar from home page
=> Add subject search

app/assets/stylesheets/components/_navbar.scss, app/controllers/favourites_controller.rb, app/controllers/jobs_controller.rb, app/views/shared/_job_profile.html.erb
- Fix on jobs controller to display all jobs when subject has no associated jobs
=> fix subject empty search results

app/assets/stylesheets/components/_job_profile.scss, app/views/jobs/new.html.erb, app/views/shared/_job_profile.html.erb
- Button on profile nav bar fills container when active
=> btn fills navbar

app/controllers/jobs_controller.rb, app/views/jobs/new.html.erb, app/views/shared/_job_profile.html.erb, db/migrate/20230923162417_add_degree_to_jobs.rb, db/schema.rb
- Added Degree to job model as boolean
=> Degree boolean added to job model and form
